create database QuanLiThuVien
use QuanLiThuVien
set dateformat dmy


CREATE TABLE SACH (	
	MASACH INT IDENTITY PRIMARY KEY,	
	TENSACH NVARCHAR(100) NOT NULL,
	NGAYXUATBAN	 SMALLDATETIME ,
	NGAYTHEMSACH SMALLDATETIME DEFAULT GETDATE(),
	GIATRI INT,  -- giá sách
	ISBN NVARCHAR(100) , 
	MATHELOAISACH INT, --KHÓA NGOẠI CỦA TABLE THELOAISACH
	MANHAXUATBAN INT, -- KHÓA NGOẠI CỦA TABLE NHATXUATBAN
	MAHIENTRANG INT DEFAULT 2,  ---- KHÓA NGOẠI CỦA HIỆN TRẠNG SÁCH
)

CREATE TABLE HIENTRANG( 
MAHIENTRANG INT PRIMARY KEY,
TENHIENTRANG NVARCHAR(100)
)


CREATE TABLE THELOAISACH
(
	MATHELOAISACH INT IDENTITY NOT NULL PRIMARY KEY,
	TENTHELOAI NVARCHAR(30) NOT NULL,
)
CREATE TABLE TACGIA
(
	MATACGIA INT IDENTITY  PRIMARY KEY,
	TENTACGIA NVARCHAR(50) NOT NULL,
)
CREATE TABLE SANGTAC 
(
	MATACGIA INT NOT NULL,  --- KHÓA NGOẠI CỦA BẢNG TÁC GIẢ
	MASACH INT NOT NULL,    --- KHÓA NGOẠI CỦA BẢNG MÃ SÁCH
	CONSTRAINT PK_SANGTAC PRIMARY KEY (MATACGIA,MASACH)  
)
CREATE TABLE NHAXUATBAN
(
	MANHAXUATBAN INT IDENTITY PRIMARY KEY,
	TENNHAXUATBAN NVARCHAR(30) NOT NULL,
)
CREATE TABLE DOCGIA
(
	MADOCGIA INT IDENTITY PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL,
	DIACHI NVARCHAR(100) ,
	EMAIL NVARCHAR(100) ,
	MACONGVIEC INT , --- KHÓA NGOẠI CỦA BẢNG CÔNG VIỆC
	NGAYSINH SMALLDATETIME ,
	GIOITINH NVARCHAR(30), -- NAM , NỮ , KHÔNG XÁC ĐỊNH
	SODIENTHOAI NVARCHAR(30) ,
	NGAYTAOTHE SMALLDATETIME DEFAULT GETDATE(),
	SONO INT DEFAULT 0
)


CREATE TABLE CONGVIEC
(
	MACONGVIEC INT IDENTITY PRIMARY KEY,
	LOAICONGVIEC NVARCHAR(50) NOT NULL,
)

CREATE TABLE THAMSO
(
	MATHAMSO INT IDENTITY  PRIMARY KEY,
	TENTHAMSO NVARCHAR(80) NOT NULL,
	GIATRITHAMSO INT NOT NULL,
)
CREATE TABLE PHIEUMUON
(
	MAPHIEUMUON INT IDENTITY  PRIMARY KEY,
	NGAYMUON SMALLDATETIME DEFAULT GETDATE(),
	MADOCGIA INT, -- KHÓA NGOẠI CỦA DOCGIA
)

CREATE TABLE CT_PHIEUMUON
(
	MACTPHIEUMUON INT IDENTITY PRIMARY KEY,
	MASACH INT, --KHÓA NGOẠI CỦA SACH
	MAPHIEUMUON INT,--KHÓA NGOẠI CỦA PHIEUMUON
	TINHTRANGPM INT DEFAULT 1, -- 0. ĐÃ TRẢ  1.CHƯA TRẢ
)




CREATE TABLE PHIEUTRA
(
	MAPHIEUTRA INT IDENTITY PRIMARY KEY,
	MADOCGIA INT, --KHÓA NGOẠI CỦA DOCGIA
	NGAYTRA SMALLDATETIME DEFAULT GETDATE(),
	TONGTIENPHAT INT DEFAULT 0-- TỔNG TIỀN PHẠT CỦA TẤT CẢ CÁC CT_PHIEUTRA
)

CREATE TABLE CT_PHIEUTRA
(
	MACTPHIEUTRA INT IDENTITY  PRIMARY KEY,
	MASACH INT,			--KHÓA NGOẠI CỦA SACH
	MAPHIEUTRA INT,		--KHÓA NGOẠI CỦA PHIEUTRA
	MAPHIEUMUON INT,	--KHÓA NGOẠI CỦA PHIEUMUON
	TIENPHAT INT DEFAULT 0, 
)

CREATE TABLE NHANVIEN
(	
	MANV INT IDENTITY PRIMARY KEY,
	TENNV NVARCHAR(30) NOT NULL,
	NGAYSINH SMALLDATETIME ,
	DIACHI NVARCHAR(50) NOT NULL,
	EMAIL NVARCHAR(50) NOT NULL,
	GIOITINH NVARCHAR(30), -- NAM , NỮ , KHÔNG XÁC ĐỊNH
	SODT NVARCHAR(20) NOT NULL,
	TAIKHOAN NVARCHAR(30) NOT NULL DEFAULT  'ACCOUNT',
	MATKHAU NVARCHAR(30) NOT NULL DEFAULT '123' ,
	MAQUYEN INT ,-- 1 là thủ thư , 0 là nhân viên
)

CREATE TABLE QUYENHAN -- quyền hạn
(
	MAQUYEN INT PRIMARY KEY, 
	TENQUYEN NVARCHAR(30) NOT NULL,
)

CREATE TABLE PHIEUTHANHTOAN
(
	MAPHIEUTHANHTOAN INT IDENTITY PRIMARY KEY,
	MANV INT NOT NULL, -- KHÓA NGOẠI CỦA NHANVIEN
	MADOCGIA INT NOT NULL, --- KHÓA NGOẠI CỦA BẢNG ĐOCGIA
	SOTIENTHANHTOAN INT NOT NULL,
	NGAYTHANHTOAN SMALLDATETIME DEFAULT GETDATE(),
	GHICHUTHANHTOAN NVARCHAR(100),
)


---------------------------TẠO KHÓA NGOẠI CHO BẢNG 
---- BẢNG SÁCH
ALTER TABLE SACH  ADD CONSTRAINT  FK_MATHELOAISACH  FOREIGN KEY (MATHELOAISACH)  REFERENCES THELOAISACH(MATHELOAISACH)
ALTER TABLE SACH  ADD CONSTRAINT  FK_MANHAXUATBAN  FOREIGN KEY (MANHAXUATBAN)  REFERENCES NHAXUATBAN(MANHAXUATBAN)
ALTER TABLE SACH ADD CONSTRAINT   FK_HIENTRANG FOREIGN KEY (MAHIENTRANG) REFERENCES HIENTRANG(MAHIENTRANG)

--- BẢNG SÁNG TÁC
ALTER TABLE SANGTAC ADD CONSTRAINT FK_MATACGIA FOREIGN KEY(MATACGIA) REFERENCES TACGIA(MATACGIA)
ALTER TABLE SANGTAC ADD CONSTRAINT FK_MASACH FOREIGN KEY(MASACH) REFERENCES SACH(MASACH)

--- BẢNG ĐỘC GIẢ
ALTER TABLE DOCGIA ADD CONSTRAINT FK_MACONGVIEC FOREIGN KEY(MACONGVIEC) REFERENCES CONGVIEC(MACONGVIEC)

--- BẢNG PHIẾU MƯỢN
ALTER TABLE PHIEUMUON	ADD CONSTRAINT  FK_MADOCGIA  FOREIGN KEY (MADOCGIA)  REFERENCES DOCGIA(MADOCGIA)

--- BẢNG CHI TIẾT PHIẾU MƯỢN
ALTER TABLE CT_PHIEUMUON 	ADD CONSTRAINT  FK_CTPHIEUMUON_MAPHIEUMUON  FOREIGN KEY (MAPHIEUMUON)  REFERENCES PHIEUMUON(MAPHIEUMUON)
ALTER TABLE CT_PHIEUMUON 	ADD CONSTRAINT  FK_CTPPHIEUMUON_MASACH FOREIGN KEY (MASACH)  REFERENCES SACH(MASACH)

--- BẢNG PHIẾU TRẢ
ALTER TABLE PHIEUTRA 	ADD CONSTRAINT  FK_PHIEUTRA_MADOCGIA FOREIGN KEY (MADOCGIA)  REFERENCES DOCGIA(MADOCGIA)

--- BẢNG CHI TIẾT PHIẾU TRẢ
ALTER TABLE CT_PHIEUTRA 	ADD CONSTRAINT  FK_CTPHIEUTRA_MASACH FOREIGN KEY (MASACH)  REFERENCES SACH(MASACH)
ALTER TABLE CT_PHIEUTRA	ADD CONSTRAINT  FK_CTPHIEUTRA_MAPHIEUTRA FOREIGN KEY (MAPHIEUTRA)  REFERENCES PHIEUTRA(MAPHIEUTRA)
ALTER TABLE CT_PHIEUTRA	ADD CONSTRAINT  FK_CTPHIEUTRA_MAPHIEUMUON FOREIGN KEY (MAPHIEUMUON)  REFERENCES PHIEUMUON(MAPHIEUMUON)

--- BẢNG NHÂN VIÊN
ALTER TABLE NHANVIEN 	ADD CONSTRAINT  FK_MAQUYEN FOREIGN KEY (MAQUYEN)  REFERENCES QUYENHAN(MAQUYEN)
	
--- BẢNG THANH TOÁN

ALTER TABLE PHIEUTHANHTOAN	ADD CONSTRAINT  FK_MANV  FOREIGN KEY (MANV)  REFERENCES NHANVIEN(MANV)
ALTER TABLE PHIEUTHANHTOAN ADD CONSTRAINT FK_BANGTHANHTOAN_MADOCGIA FOREIGN KEY(MADOCGIA) REFERENCES DOCGIA(MADOCGIA)

-------------------------------------TẠO TRIGGER CHO BẢNG
 --- TỔNG TIỀN PHẠT CỦA PHIẾU TRẢ BĂNG TỔNG TIỀN PHẠT CỦA CT PHIẾU TRẢ 
 CREATE TRIGGER UPDATE_TONGTIENPHAT_PHIEUTRA
 ON CT_PHIEUTRA
 FOR INSERT, UPDATE
 AS
 BEGIN

	DECLARE @TIENPHAT INT 
	DECLARE @TONGTIENPHAT INT = 0
	DECLARE @MAPHIEUTRA INT
	SELECT @MAPHIEUTRA = MAPHIEUTRA, @TIENPHAT = TIENPHAT FROM inserted 
	SELECT @TONGTIENPHAT = TONGTIENPHAT FROM PHIEUTRA WHERE MAPHIEUTRA = @MAPHIEUTRA
	SET @TONGTIENPHAT  = @TONGTIENPHAT + @TIENPHAT

	UPDATE PHIEUTRA
	SET TONGTIENPHAT = @TONGTIENPHAT
	WHERE MAPHIEUTRA = @MAPHIEUTRA	
 END

 CREATE TRIGGER UPDATE_TONGTIENPHAT_PHIEUTRA_FOR_DELETE
 ON CT_PHIEUTRA
 FOR DELETE
 AS
 BEGIN

	DECLARE @TIENPHAT INT 
	DECLARE @TONGTIENPHAT INT = 0
	DECLARE @MAPHIEUTRA INT
	SELECT @MAPHIEUTRA = MAPHIEUTRA, @TIENPHAT = TIENPHAT FROM deleted
	SELECT @TONGTIENPHAT = TONGTIENPHAT FROM PHIEUTRA WHERE MAPHIEUTRA = @MAPHIEUTRA
	SET @TONGTIENPHAT  = @TONGTIENPHAT - @TIENPHAT

	UPDATE PHIEUTRA
	SET TONGTIENPHAT = @TONGTIENPHAT
	WHERE MAPHIEUTRA = @MAPHIEUTRA	
 END


 ---- SET CT_PHIẾU MƯỢN = ĐÃ TRẢ KHI ĐÃ TRẢ
 CREATE TRIGGER UPDATE_PHIEUMUON
 ON CT_PHIEUTRA
 FOR INSERT, UPDATE
 AS
 BEGIN
	DECLARE @MAPHIEUMUON INT
	DECLARE @MASACH INT
	SELECT @MAPHIEUMUON = MAPHIEUMUON, @MASACH = MASACH FROM inserted
	UPDATE CT_PHIEUMUON
	SET TINHTRANGPM =  0
	WHERE MASACH = @MASACH AND MAPHIEUMUON = @MAPHIEUMUON
 END


 ----- SỐ NỢ CỦA ĐỘC GIẢ SẼ BẲNG SỐ NỢ CŨ CỘNG VỚI TỔNG TIỀN PHẠT TRONG PHIẾU PHẠT KHI INSERT, UPDATE CT_PHIEUPHAT , tình trạng sách sẽ được set lại về chưa được mượn
 ALTER TRIGGER UPDATE_DOCGIA
 ON CT_PHIEUTRA
 FOR INSERT, UPDATE
 AS
 BEGIN 
	DECLARE @SONO INT 
	DECLARE @TIENPHAT INT
	DECLARE @MAPHIEUTRA INT 
	DECLARE @MADOCGIA INT
	DECLARE @MASACH INT
	SELECT @MAPHIEUTRA = MAPHIEUTRA , @MASACH = MASACH FROM inserted
	SELECT @MADOCGIA = MADOCGIA, @TIENPHAT = TONGTIENPHAT FROM PHIEUTRA WHERE MAPHIEUTRA = @MAPHIEUTRA
	select @SONO = SONO from DOCGIA where madocgia = @MADOCGIA
	SET @SONO = @SONO + @TIENPHAT
	UPDATE DOCGIA
	SET SONO = @SONO
	WHERE MADOCGIA = @MADOCGIA
	UPDATE SACH
	SET MAHIENTRANG = 2
	WHERE MASACH= @MASACH
 END
 


 ---- SỐ NỢ CỦA ĐỘC GIẢ SẼ ĐƯỢC TRỪ ĐI KHI ĐƯỢC THANH TOÁN
 CREATE TRIGGER UPDATE_DOCGIA_THANHTOAN
 ON PHIEUTHANHTOAN
 FOR INSERT , UPDATE
 AS
 BEGIN
	DECLARE @SONO INT
	DECLARE @TIENTHANHTOAN INT
	DECLARE @MADOCGIA INT
	SELECT @MADOCGIA = MADOCGIA, @TIENTHANHTOAN = SOTIENTHANHTOAN FROM inserted
	SELECT @SONO =SONO FROM DOCGIA WHERE MADOCGIA = @MADOCGIA
	SET @SONO = @SONO - @TIENTHANHTOAN
	UPDATE DOCGIA 
	SET SONO = @SONO
	WHERE MADOCGIA = @MADOCGIA

 END


 --------------INSERT DỮ LIỆU
 ----- THỂ LOẠI SÁCH
INSERT INTO THELOAISACH (TENTHELOAI) VALUES(N'SGK')
INSERT INTO THELOAISACH (TENTHELOAI) VALUES(N'TRUYỆN')
INSERT INTO THELOAISACH (TENTHELOAI) VALUES(N'TẠP CHÍ')
INSERT INTO THELOAISACH (TENTHELOAI) VALUES(N'TIỂU THUYẾT')

------ NHÀ XUẤT BẢN
INSERT INTO NHAXUATBAN (TENNHAXUATBAN) VALUES (N'NXB Tuổi trẻ')
INSERT INTO NHAXUATBAN (TENNHAXUATBAN) VALUES (N'NXB Kim Đồng')
INSERT INTO NHAXUATBAN (TENNHAXUATBAN) VALUES (N'NXB GIÁO DỤC VIỆT NAM')

------- HIỆN TRẠNG
INSERT INTO HIENTRANG (MAHIENTRANG, TENHIENTRANG) VALUES (1, N'SÁCH MỚI')
INSERT INTO HIENTRANG (MAHIENTRANG, TENHIENTRANG) VALUES (2, N'SÁCH CŨ')

------ TÁC GIẢ
INSERT INTO TACGIA ( TENTACGIA ) VALUES (N'NGUYỄN NHẬT ÁNH')
INSERT INTO TACGIA ( TENTACGIA ) VALUES (N'NGUYỄN NGỌC NGẠN')
INSERT INTO TACGIA( TENTACGIA ) VALUES ( N'ĐỖ NGUYỄN NHẬT LINH')


--- QUYỀN HẠN
INSERT INTO QUYENHAN(MAQUYEN,TENQUYEN) VALUES ('1',N'Thủ Thư')
INSERT INTO QUYENHAN(MAQUYEN,TENQUYEN) VALUES ('0',N'Nhân Viên')

SELECT * FROM THELOAISACH
SELECT * FROM NHAXUATBAN

---- SÁCH
INSERT INTO SACH(TENSACH ,	NGAYXUATBAN ,	GIATRI,	ISBN  , MATHELOAISACH, MANHAXUATBAN, MAHIENTRANG)
VALUES (N'TRẠNG TÍ', '21/12/2020', 15000, '0-306-40615-2' , 2,1, 2)
INSERT INTO SACH(TENSACH ,	NGAYXUATBAN ,	GIATRI,	ISBN  , MATHELOAISACH, MANHAXUATBAN, MAHIENTRANG)
VALUES (N'MẮT BIẾC', '21/12/2021', 15000, '0-306-40615-2' , 2,1, 2)
INSERT INTO SACH(TENSACH ,	NGAYXUATBAN ,	GIATRI,	ISBN  , MATHELOAISACH, MANHAXUATBAN, MAHIENTRANG)
VALUES (N'MÔN TOÁN LỚP 2', '21/12/2020', 15000, '0-306-40615-2' , 1,3, 2)
INSERT INTO SACH(TENSACH ,	NGAYXUATBAN ,	GIATRI,	ISBN  , MATHELOAISACH, MANHAXUATBAN, MAHIENTRANG)
VALUES (N'TIỂU THUYẾT TUỔI THANH XUÂN', '21/12/2020', 15000, '0-306-40615-2' , 4,2, 2)
INSERT INTO SACH(TENSACH ,	NGAYXUATBAN ,	GIATRI,	ISBN  , MATHELOAISACH, MANHAXUATBAN, MAHIENTRANG)
VALUES (N'TẠP CHÍ XANH', '21/12/2020', 15000, '0-306-40615-2' , 3,2, 2)

---- SÁNG TÁC
SELECT * FROM SACH

INSERT INTO SANGTAC (MATACGIA, MASACH) VALUES (3,7)
INSERT INTO SANGTAC (MATACGIA, MASACH) VALUES( 1,8)
INSERT INTO SANGTAC (MATACGIA, MASACH) VALUES (3,9)
INSERT INTO SANGTAC (MATACGIA, MASACH) VALUES (3,10)
INSERT INTO SANGTAC (MATACGIA, MASACH) VALUES (3,11)

----- CÔNG VIỆC
INSERT INTO CONGVIEC
VALUES (N'HỌC SINH')
INSERT INTO CONGVIEC
VALUES (N'SINH VIÊN')
INSERT INTO CONGVIEC
VALUES (N'GIÁO VIÊN')


---- DOC GIA
SELECT * FROM DOCGIA
INSERT INTO DOCGIA(HOTEN, DIACHI, EMAIL, MACONGVIEC, NGAYSINH, GIOITINH, SODIENTHOAI, SONO)
VALUES (N'Hoàng Xuân Vũ', 'KTX Khu A', N'xuanvuzzz2601', 1, '26/01/2001', 'NAM', '1234567890', 0)
INSERT INTO DOCGIA(HOTEN, DIACHI, EMAIL, MACONGVIEC, NGAYSINH, GIOITINH, SODIENTHOAI, SONO)
VALUES (N'Lê Văn Nhân', 'KTX Khu A', N'nhanvippro', 2, '27/01/2001', 'NAM', '1234567890', 0)
INSERT INTO DOCGIA(HOTEN, DIACHI, EMAIL, MACONGVIEC, NGAYSINH, GIOITINH, SODIENTHOAI, SONO)
VALUES (N'Lê Dương Khánh Việt', 'KTX Khu B', N'vietvippro', 2, '28/01/2001', 'NAM', '1234567890', 0)
INSERT INTO DOCGIA(HOTEN, DIACHI, EMAIL, MACONGVIEC, NGAYSINH, GIOITINH, SODIENTHOAI, SONO)
VALUES (N'Đỗ Nguyễn Hoàng Huy' , 'KTX Khu A', N'huyvippro', 3, '29/01/2001', 'NAM', '1234567890', 0)

----- NHANVIEN
INSERT INTO NHANVIEN (TENNV, NGAYSINH, DIACHI, EMAIL, GIOITINH, SODT, TAIKHOAN, MATKHAU, MAQUYEN)
VALUES (N'LÊ VĂN A', '20/01/2001', N'NHÀ CÔNG VỤ KHU A', 'ALEVAN@GMAIL.COM', 'NAM', '012345678', 'ACCOUNT1', '123', 1)
INSERT INTO NHANVIEN (TENNV, NGAYSINH, DIACHI, EMAIL, GIOITINH, SODT, TAIKHOAN, MATKHAU, MAQUYEN)
VALUES (N'LÊ VĂN B', '20/01/2001', N'NHÀ CÔNG VỤ KHU B', 'BLEVAN@GMAIL.COM', 'NAM', '012345678', 'ACCOUNT2', '123', 0)


----- PHIEU MUON
SELECT * FROM PHIEUMUON

INSERT INTO PHIEUMUON (MADOCGIA)
VALUES (1)
INSERT INTO PHIEUMUON (MADOCGIA)
VALUES (2)


---- THAMSO
INSERT INTO THAMSO (TENTHAMSO, GIATRITHAMSO)
VALUES(N'Độ tuổi mượn tối thiểu', 15)
INSERT INTO THAMSO ( TENTHAMSO, GIATRITHAMSO)
VALUES(N'Độ tuổi mượn tối đa', 55)
INSERT INTO THAMSO (TENTHAMSO, GIATRITHAMSO)
VALUES(N'Số ngày mượn tối đa', 7)
INSERT INTO THAMSO (TENTHAMSO, GIATRITHAMSO)
VALUES(N'Giá tiền phạt trễ/ngày', 1000)

select * from thamso




 --- CHI TIẾT PHIẾU MƯỢN
--INSERT INTO CT_PHIEUMUON( MASACH, MAPHIEUMUON)
--VALUES ( 2,3)
--INSERT INTO CT_PHIEUMUON (MASACH, MAPHIEUMUON)
--VALUES (3,3)
--INSERT INTO CT_PHIEUMUON (MASACH, MAPHIEUMUON)
--VALUES (4,4)
--INSERT INTO CT_PHIEUMUON (MASACH, MAPHIEUMUON)
--VALUES (6,4)


---- PHIẾU TRẢ

--INSERT INTO PHIEUTRA (MADOCGIA, TONGTIENPHAT)
--VALUES (5, 10000)
--INSERT INTO PHIEUTRA(MADOCGIA, TONGTIENPHAT)
--VALUES (5,0)

----- CT PHIẾU TRẢ
--INSERT INTO CT_PHIEUTRA(MASACH, MAPHIEUTRA, MAPHIEUMUON, TIENPHAT)
--VALUES (2, 1,2, 20000)
--INSERT INTO CT_PHIEUTRA(MASACH, MAPHIEUTRA, MAPHIEUMUON, TIENPHAT)
--VALUES (3, 1, 2,0)


-- PROC login
CREATE PROC USP_LOGIN
@TAIKHOAN NVARCHAR(100),@MATKHAU NVARCHAR(100)
AS
BEGIN
	SELECT * 
	FROM NHANVIEN
	WHERE TAIKHOAN = @TAIKHOAN AND MATKHAU = @MATKHAU
END

EXEC USP_LOGIN @TAIKHOAN = 'ACCOUNT1', @MATKHAU = '123'

-- PROC ĐỔI MẬT KHẨU
CREATE PROC USP_CHANGEPASSWORD
@TAIKHOAN NVARCHAR(100), @MATKHAUMOI NVARCHAR(100)
AS
BEGIN
	UPDATE NHANVIEN
	SET MATKHAU = @MATKHAUMOI
	WHERE TAIKHOAN =@TAIKHOAN
END

-- PROC bỏ dấu chuỗi
CREATE FUNCTION [dbo].[GetUnsignString](@strInput NVARCHAR(4000)) 
RETURNS NVARCHAR(4000)
AS
BEGIN     
    IF @strInput IS NULL RETURN @strInput
    IF @strInput = '' RETURN @strInput
    DECLARE @RT NVARCHAR(4000)
    DECLARE @SIGN_CHARS NCHAR(136)
    DECLARE @UNSIGN_CHARS NCHAR (136)

    SET @SIGN_CHARS       = N'ăâđêôơưàảãạáằẳẵặắầẩẫậấèẻẽẹéềểễệếìỉĩịíòỏõọóồổỗộốờởỡợớùủũụúừửữựứỳỷỹỵýĂÂĐÊÔƠƯÀẢÃẠÁẰẲẴẶẮẦẨẪẬẤÈẺẼẸÉỀỂỄỆẾÌỈĨỊÍÒỎÕỌÓỒỔỖỘỐỜỞỠỢỚÙỦŨỤÚỪỬỮỰỨỲỶỸỴÝ'+NCHAR(272)+ NCHAR(208)
    SET @UNSIGN_CHARS = N'aadeoouaaaaaaaaaaaaaaaeeeeeeeeeeiiiiiooooooooooooooouuuuuuuuuuyyyyyAADEOOUAAAAAAAAAAAAAAAEEEEEEEEEEIIIIIOOOOOOOOOOOOOOOUUUUUUUUUUYYYYYDD'

    DECLARE @COUNTER int
    DECLARE @COUNTER1 int
    SET @COUNTER = 1
 
    WHILE (@COUNTER <=LEN(@strInput))
    BEGIN   
      SET @COUNTER1 = 1
      --Tim trong chuoi mau
       WHILE (@COUNTER1 <=LEN(@SIGN_CHARS)+1)
       BEGIN
     IF UNICODE(SUBSTRING(@SIGN_CHARS, @COUNTER1,1)) = UNICODE(SUBSTRING(@strInput,@COUNTER ,1) )
     BEGIN           
          IF @COUNTER=1
              SET @strInput = SUBSTRING(@UNSIGN_CHARS, @COUNTER1,1) + SUBSTRING(@strInput, @COUNTER+1,LEN(@strInput)-1)                   
          ELSE
              SET @strInput = SUBSTRING(@strInput, 1, @COUNTER-1) +SUBSTRING(@UNSIGN_CHARS, @COUNTER1,1) + SUBSTRING(@strInput, @COUNTER+1,LEN(@strInput)- @COUNTER)    
              BREAK         
               END
             SET @COUNTER1 = @COUNTER1 +1
       END
      --Tim tiep
       SET @COUNTER = @COUNTER +1
    END
    RETURN @strInput
END

--- ------------------------------------------------
CREATE PROC USP_GET_PERMISSION_BY_IDPERMISSION
@IDPERMISSION INT
AS
BEGIN
	select * from QUYENHAN where MAQUYEN = @IDPERMISSION
END

---------------------------------------------------
ALTER PROC USP_GETLISTBOOKBYIDBOOK
@IDBOOK int
AS 
BEGIN
	
	select A.MASACH AS N'Mã sách', A.TENSACH AS N'Tên sách' , B.TENTACGIA AS N'Tên tác giả',D.TENNHAXUATBAN AS N'Tên nhà XB', A.NGAYXUATBAN AS N'Ngày xuất bản', A.NGAYTHEMSACH AS N'Ngày thêm sách', A.GIATRI AS N'Giá trị', A.ISBN, C.TENTHELOAI AS N'Thể loại sách' , HIENTRANG.TENHIENTRANG AS N'Hiện trạng'
	FROM SACH A JOIN SANGTAC ON A.MASACH = SANGTAC.MASACH JOIN TACGIA B ON SANGTAC.MATACGIA = B.MATACGIA JOIN THELOAISACH C ON A.MATHELOAISACH = C.MATHELOAISACH JOIN HIENTRANG ON A.MAHIENTRANG = HIENTRANG.MAHIENTRANG JOIN NHAXUATBAN D ON A.MANHAXUATBAN=D.MANHAXUATBAN WHERE  dbo.GetUnsignString(A.MASACH)  like N'%' + dbo.GetUnsignString(@IDBOOK) + '%'		
END

-----------------------------------------------------
ALTER PROC USP_GETLISTBOOKBYNAMEBOOK
@NAMEBOOK NVARCHAR(100)
AS 
BEGIN	
	 select A.MASACH AS N'Mã sách', A.TENSACH AS N'Tên sách' , B.TENTACGIA AS N'Tên tác giả',D.TENNHAXUATBAN AS N'Tên nhà XB', A.NGAYXUATBAN AS N'Ngày xuất bản', A.NGAYTHEMSACH AS N'Ngày thêm sách', A.GIATRI AS N'Giá trị', A.ISBN, C.TENTHELOAI AS N'Thể loại sách' , HIENTRANG.TENHIENTRANG AS N'Hiện trạng'
	FROM SACH A JOIN SANGTAC ON A.MASACH = SANGTAC.MASACH JOIN TACGIA B ON SANGTAC.MATACGIA = B.MATACGIA JOIN THELOAISACH C ON A.MATHELOAISACH = C.MATHELOAISACH JOIN HIENTRANG ON A.MAHIENTRANG = HIENTRANG.MAHIENTRANG JOIN NHAXUATBAN D ON A.MANHAXUATBAN=D.MANHAXUATBAN WHERE  dbo.GetUnsignString(TENSACH)  like N'%' + dbo.GetUnsignString(@NAMEBOOK) + '%'		
END

-----------------------------------------------------
ALTER PROC USP_GETLISTBOOKBYNAMECATEGORY
@NAMECATEGORY NVARCHAR(100)
AS 
BEGIN	
	select A.MASACH AS N'Mã sách', A.TENSACH AS N'Tên sách' , B.TENTACGIA AS N'Tên tác giả',D.TENNHAXUATBAN AS N'Tên nhà XB', A.NGAYXUATBAN AS N'Ngày xuất bản', A.NGAYTHEMSACH AS N'Ngày thêm sách', A.GIATRI AS N'Giá trị', A.ISBN, C.TENTHELOAI AS N'Thể loại sách' , HIENTRANG.TENHIENTRANG AS N'Hiện trạng'
	FROM SACH A JOIN SANGTAC ON A.MASACH = SANGTAC.MASACH JOIN TACGIA B ON SANGTAC.MATACGIA = B.MATACGIA JOIN THELOAISACH C ON A.MATHELOAISACH = C.MATHELOAISACH JOIN HIENTRANG ON A.MAHIENTRANG = HIENTRANG.MAHIENTRANG JOIN NHAXUATBAN D ON A.MANHAXUATBAN = D.MANHAXUATBAN WHERE  dbo.GetUnsignString(TENTHELOAI)  like N'%' + dbo.GetUnsignString(@NAMECATEGORY) + '%'		
END

---------------------------------------------------
ALTER PROC USP_GETLISTBOOKBYNAMEAUTHOR
@NAMEAUTHOR NVARCHAR(100)
AS 
BEGIN	
	select A.MASACH AS N'Mã sách', A.TENSACH AS N'Tên sách' , B.TENTACGIA AS N'Tên tác giả',NHAXUATBAN.TENNHAXUATBAN AS N'Tên nhà XB', A.NGAYXUATBAN AS N'Ngày xuất bản', A.NGAYTHEMSACH AS N'Ngày thêm sách', A.GIATRI AS N'Giá trị', A.ISBN, C.TENTHELOAI AS N'Thể loại sách' , HIENTRANG.TENHIENTRANG AS N'Hiện trạng'
	FROM SACH A JOIN SANGTAC ON A.MASACH = SANGTAC.MASACH JOIN TACGIA B ON SANGTAC.MATACGIA = B.MATACGIA JOIN THELOAISACH C ON A.MATHELOAISACH = C.MATHELOAISACH JOIN HIENTRANG ON A.MAHIENTRANG = HIENTRANG.MAHIENTRANG join NHAXUATBAN on A.MANHAXUATBAN=NHAXUATBAN.MANHAXUATBAN WHERE  dbo.GetUnsignString(TENTACGIA)  like N'%' + dbo.GetUnsignString(@NAMEAUTHOR) + '%'			 
END

------------------------------------------
ALTER PROC USP_GETLISTBOOK
AS 
BEGIN	
	select A.MASACH AS N'Mã sách', A.TENSACH AS N'Tên sách' , B.TENTACGIA AS N'Tên tác giả',NHAXUATBAN.TENNHAXUATBAN AS N'Tên nhà XB', A.NGAYXUATBAN AS N'Ngày xuất bản', A.NGAYTHEMSACH AS N'Ngày thêm sách', A.GIATRI AS N'Giá trị', A.ISBN, C.TENTHELOAI AS N'Thể loại sách' , HIENTRANG.TENHIENTRANG AS N'Hiện trạng'
	FROM SACH A JOIN SANGTAC ON A.MASACH = SANGTAC.MASACH JOIN TACGIA B ON SANGTAC.MATACGIA = B.MATACGIA JOIN THELOAISACH C ON A.MATHELOAISACH = C.MATHELOAISACH JOIN HIENTRANG ON A.MAHIENTRANG = HIENTRANG.MAHIENTRANG 	Join NHAXUATBAN on A.MANHAXUATBAN = NhaXuatban.MANHAXUATBAN		 
END

--------------------------------------------
ALTER PROC USP_GETLISTREADER
AS
BEGIN 
	SELECT	MADOCGIA, CAST(MADOCGIA AS NVARCHAR(100)) + '  ' + HOTEN AS HOTEN, DIACHI, EMAIL, MACONGVIEC, NGAYSINH, GIOITINH,SODIENTHOAI, NGAYTAOTHE, SONO FROM DOCGIA
END

-------------------------------------------
CREATE PROC USP_GETLISTBILLBORROW
AS
BEGIN 
	SELECT * FROM PHIEUMUON
END

------------------------------------------
CREATE PROC USP_GETLISTBILLRETURN
AS
BEGIN 
	SELECT * FROM PHIEUTRA
END
-----------------------------------------------
CREATE PROC USP_INSERTBILLBORROW
@IDREADER INT, @DATEINSERT SMALLDATETIME
AS
BEGIN
	INSERT INTO PHIEUMUON (NGAYMUON, MADOCGIA)
	VALUES (@DATEINSERT, @IDREADER)
END

---------------------------------------------------
CREATE PROC USP_GETDETAILBILLBORROWBYIDBILLBORROW
@IDBILLBORROW INT
AS
BEGIN
	SELECT * FROM CT_PHIEUMUON WHERE MAPHIEUMUON = @IDBILLBORROW
END

---------------------------------------------------
ALTER PROC USP_INSERTDETAILBILLBORROW
@IDBOOK INT, @IDBILLBORROW INT
AS
BEGIN
	DECLARE @MAHIENTRANG INT
	SELECT @MAHIENTRANG = MAHIENTRANG FROM SACH WHERE MASACH = @IDBOOK
	IF @MAHIENTRANG = 2
	BEGIN 

		INSERT INTO CT_PHIEUMUON (MASACH, MAPHIEUMUON)
		VALUES (@IDBOOK, @IDBILLBORROW)

		UPDATE SACH
		SET MAHIENTRANG = 1
		WHERE MASACH = @IDBOOK
	END
END



CREATE PROC USP_INSERTBILLRETURN
@IDREADER INT, @DATERETURN SMALLDATETIME
AS 
BEGIN
	INSERT INTO PHIEUTRA(MADOCGIA,NGAYTRA)
	VALUES( @IDREADER, @DATERETURN)
END

ALTER PROC USP_GETLISTIDREADERFROMBILLBORROW
AS
BEGIN
	SELECT MADOCGIA,CAST(MADOCGIA AS NVARCHAR(100)) + ' ' +  HOTEN AS HOTEN, DIACHI, EMAIL, MACONGVIEC,NGAYSINH, GIOITINH, SODIENTHOAI, NGAYTAOTHE, SONO FROM DOCGIA
	WHERE MADOCGIA IN ( 
	SELECT MADOCGIA
	FROM PHIEUMUON)
END

-----------------------------------------------
CREATE PROC USP_GETLISTBILLBORROWBYIDREADER
@IDREADER INT
AS
BEGIN
	SELECT * FROM PHIEUMUON WHERE MADOCGIA = @IDREADER
END

---------------------------------------------------
CREATE PROC USP_GETLISTDETAILBILLRETURNBYIDBILLRETURN
@IDBILLRETURN INT
AS
BEGIN
	SELECT * FROM CT_PHIEUTRA WHERE MAPHIEUTRA = @IDBILLRETURN
END



---------------------------------------------------
ALTER PROC USP_INSERTDETAILBILLRETURN
@IDBILLRETURN INT , @IDBOOK INT, @IDBILLBORROW INT , @FINE INT
AS
BEGIN
	declare @count int
	select @count = count(*) from CT_PHIEUTRA where MAPHIEUTRA = @IDBILLRETURN and masach = @idbook
	if @count = 0
	begin
	INSERT INTO CT_PHIEUTRA (MASACH, MAPHIEUTRA, MAPHIEUMUON, TIENPHAT)
	VALUES(@IDBOOK, @IDBILLRETURN, @IDBILLBORROW, @FINE)
	end
END

---------------------------------------------------
select * from sach
where masach in
(select masach from ct_phieumuon where MAPHIEUMUON = 3 and tinhtrangpm = 1)


ALTER PROC GETLISTBOOKFORDETAILBILLRETURN
@IDBILLBORROW INT
AS
BEGIN
	SELECT MASACH, CAST (MASACH AS NVARCHAR(100)) + ' ' +  TENSACH AS TENSACH, NGAYXUATBAN, NGAYTHEMSACH, GIATRI, ISBN, MATHELOAISACH, MANHAXUATBAN, MAHIENTRANG  FROM SACH WHERE MASACH IN
	(
	SELECT MASACH FROM CT_PHIEUMUON WHERE TINHTRANGPM = 1 AND MAPHIEUMUON = @IDBILLBORROW
	)
END

-----------------------------------------
ALTER PROC INSERTPAYMENT
@IDSTAFF INT, @IDREADER INT , @MONEY INT , @DATEPAYMENT SMALLDATETIME, @NOTE NVARCHAR(100)
AS
BEGIN
	INSERT INTO PHIEUTHANHTOAN(MANV, MADOCGIA, SOTIENTHANHTOAN, NGAYTHANHTOAN, GHICHUTHANHTOAN)
	VALUES (@IDSTAFF, @IDREADER, @MONEY, @DATEPAYMENT, @NOTE)
END

CREATE PROC INSERTINTOBOOK
@NAMEBOOK NVARCHAR(100), @DATEPUBLISHER SMALLDATETIME, @DATEADD SMALLDATETIME , @VALUE INT , @ISBN NVARCHAR(100), @IDCATE INT , @IDPUBLISHER INT , @idauthor int
AS
BEGIN
	declare @masach int
	INSERT INTO SACH(TENSACH, NGAYXUATBAN, NGAYTHEMSACH, GIATRI, ISBN, MATHELOAISACH, MANHAXUATBAN)
	VALUES(@NAMEBOOK, @DATEPUBLISHER,@DATEADD, @VALUE, @ISBN, @IDCATE, @IDPUBLISHER)
	select @masach = max(masach) from SACH
	insert into SANGTAC (MASACH, MATACGIA)
	values(@masach, @idauthor)
END

ALTER PROC DELBOOK
@IDBOOK INT , @IDAUTHOR INT
AS
BEGIN
	DECLARE @IDHIENTRANG INT

	SELECT @IDHIENTRANG= MAHIENTRANG FROM SACH WHERE MASACH  = @IDBOOK
	IF (@IDHIENTRANG = 2)
	BEGIN
		DELETE SANGTAC
		WHERE MASACH = @IDBOOK AND MATACGIA = @IDAUTHOR
		DELETE SACH
		WHERE MASACH = @IDBOOK
	END
END

alter PROC UPDATEBOOK
@IDBOOK INT, @NAMEBOOK NVARCHAR(100), @DATEPUBLISHER SMALLDATETIME, @DATEADD SMALLDATETIME , @VALUE INT , @ISBN NVARCHAR(100), @IDCATE INT , @IDPUBLISHER INT , @idauthor int
AS
BEGIN

	UPDATE SANGTAC
	SET MATACGIA = @idauthor
	WHERE MASACH = @IDBOOK
	UPDATE SACH 
	SET TENSACH = @NAMEBOOK, NGAYXUATBAN = @DATEPUBLISHER, NGAYTHEMSACH = @DATEADD, GIATRI = @VALUE, ISBN = @ISBN , MATHELOAISACH = @IDCATE, MANHAXUATBAN = @IDPUBLISHER
	where  masach = @idbook
END

CREATE PROC GETLISTREADER
AS
BEGIN
	SELECT MADOCGIA, HOTEN, DIACHI, EMAIL, LOAICONGVIEC, NGAYSINH, GIOITINH, SODIENTHOAI, NGAYTAOTHE, SONO FROM DOCGIA JOIN CONGVIEC ON DOCGIA.MACONGVIEC = CONGVIEC.MACONGVIEC
END

CREATE PROC INSERTREADER
@NAME NVARCHAR(100), @ADDRESS NVARCHAR(100), @EMAIL NVARCHAR(100), @IDWORK INT , @DOB SMALLDATETIME, @SEX NVARCHAR(30), @PHONE NVARCHAR(100), @DATECREATE SMALLDATETIME, @DEBT INT
AS
BEGIN
	INSERT INTO DOCGIA(HOTEN, DIACHI, EMAIL, MACONGVIEC, NGAYSINH, GIOITINH, SODIENTHOAI, NGAYTAOTHE, SONO)
	VALUES(@NAME, @ADDRESS, @EMAIL, @IDWORK, @DOB, @SEX, @PHONE, @DATECREATE, @DEBT)
END

CREATE PROC UPDATEREADER
@IDREADER INT, @NAME NVARCHAR(100), @ADDRESS NVARCHAR(100), @EMAIL NVARCHAR(100), @IDWORK INT , @DOB SMALLDATETIME, @SEX NVARCHAR(30), @PHONE NVARCHAR(100), @DATECREATE SMALLDATETIME, @DEBT INT
AS
BEGIN
	UPDATE DOCGIA
	SET HOTEN =@NAME, DIACHI = @ADDRESS, EMAIL =@EMAIL, MACONGVIEC = @IDWORK, NGAYSINH = @DOB , GIOITINH = @SEX , NGAYTAOTHE = @DATECREATE, SONO = @DEBT
	WHERE MADOCGIA = @IDREADER
END

ALTER PROC DELREADER
@IDREADER INT 
AS
BEGIN
	DECLARE @COUNT INT
	select @COUNT =COUNT(*) from CT_PHIEUMUON a  join phieumuon b  on a.MAPHIEUMUON = b.MAPHIEUMUON  where madocgia = @IDREADER and TINHTRANGPM = 1
	declare @no int
	select @no = sono from docgia where MADOCGIA = @IDREADER
	set @count =@count + @no
	IF (@COUNT = 0)
	BEGIN
			DELETE CT_PHIEUTRA
			WHERE MAPHIEUTRA IN 
			(
			SELECT MAPHIEUTRA 
			FROM PHIEUTRA
			WHERE MADOCGIA =  @IDREADER
			)
		
			DELETE PHIEUTRA
			WHERE MADOCGIA  =  @IDREADER

			DELETE CT_PHIEUMUON
			WHERE MAPHIEUMUON IN
				(SELECT MAPHIEUMUON
				FROM PHIEUMUON
				WHERE MADOCGIA =  @IDREADER
				)

			DELETE PHIEUMUON
			WHERE MADOCGIA = @IDREADER	

			DELETE PHIEUTHANHTOAN
			WHERE MADOCGIA = @IDREADER

			DELETE DOCGIA
			WHERE MADOCGIA = @IDREADER
	END
END

ALTER PROC INSERTSTAFF
@NAME NVARCHAR(100), @DOB SMALLDATETIME, @ADDRESS NVARCHAR(100), @EMAIL NVARCHAR(100), @SEX NVARCHAR(30), @PHONE NVARCHAR(100), @ACCOUNT NVARCHAR(100), @IDPER INT
AS
BEGIN
	declare @count int
	select @count  = count(*) from nhanvien where TAIKHOAN = @ACCOUNT
	if @count = 0
	begin
	INSERT INTO NHANVIEN (TENNV, NGAYSINH, DIACHI,EMAIL, GIOITINH,SODT, TAIKHOAN, MAQUYEN)
	VALUES (@NAME,@DOB, @ADDRESS, @EMAIL, @SEX, @PHONE, @ACCOUNT, @IDPER)
	end
END

ALTER PROC DELETE_DETAILBILLRETURN 
@IDDETAILBILLRETURN INT
AS
BEGIN
	DECLARE @IDBILLBORROW INT
	DECLARE @IDBILLRETURN INT
	DECLARE @IDBOOK INT
	SELECT @IDBILLBORROW = MAPHIEUMUON ,@IDBILLRETURN = MAPHIEUTRA, @IDBOOK = MASACH FROM CT_PHIEUTRA WHERE MACTPHIEUTRA = @IDDETAILBILLRETURN

	DECLARE @IDREADER INT, @NO INT
	SELECT @IDREADER = MADOCGIA FROM PHIEUMUON WHERE MAPHIEUMUON = @IDBILLBORROW
	SELECT @NO = SONO FROM DOCGIA WHERE MADOCGIA = @IDREADER
	IF (@NO = 0)
	BEGIN

		delete CT_PHIEUTRA
		where MACTPHIEUTRA =@IDDETAILBILLRETURN
		delete CT_PHIEUMUON
		where MAPHIEUMUON = @IDBILLBORROW and MASACH = @IDBOOK
	
		declare @count1 int , @count2 int

		select  @count2 = count(*) from CT_PHIEUTRA  where MAPHIEUTRA = @IDBILLRETURN
		if (@count2 = 0)
		begin
			delete phieutra
			where MAPHIEUTRA = @IDBILLRETURN
		end

	
		select @count1 = count(*) from CT_PHIEUMUON where MAPHIEUMUON =@IDBILLBORROW
		if (@count1 = 0)
		begin 
			delete phieumuon
			where MAPHIEUMUON = @IDBILLBORROW
		end
	end	
end

CREATE PROC DELETESTAFF
@IDSTAFF INT
AS
BEGIN
	DELETE PHIEUTHANHTOAN
	WHERE MANV = @IDSTAFF
	DELETE NHANVIEN
	WHERE MANV = @IDSTAFF	
END

alter PROC UPDATESTAFF
@IDSTAFF INT,@NAME NVARCHAR(100), @DOB SMALLDATETIME, @ADDRESS NVARCHAR(100), @EMAIL NVARCHAR(100), @SEX NVARCHAR(30), @PHONE NVARCHAR(100), @ACCOUNT NVARCHAR(100), @IDPER INT
AS
BEGIN 
	DECLARE @COUNT INT
	SELECT @COUNT = COUNT(*) FROM NHANVIEN WHERE TAIKHOAN =@ACCOUNT
	IF (@COUNT <2 )
	BEGIN
		UPDATE NHANVIEN
		SET TENNV = @NAME, NGAYSINH = @DOB, DIACHI =@ADDRESS, EMAIL = @EMAIL, GIOITINH =@SEX, SODT = @PHONE, TAIKHOAN = @ACCOUNT,MAQUYEN = @IDPER
		WHERE MANV = @IDSTAFF
	END
END


------THỐNG KÊ SÁCH TÌNH HÌNH MƯỢN SÁCH THEO THỂ LOẠI
ALTER PROC REPORTBOOKUNRETURN
@DATEFROM SMALLDATETIME, @DATETO SMALLDATETIME
AS
BEGIN
	declare @tong FLOAT
	select @tong = count(*)  from  ct_phieumuon a join phieumuon b on a.MAPHIEUMUON = b.MAPHIEUMUON
	where B.NGAYMUON >= @DATEFROM AND B.MAPHIEUMUON<= @DATETO


	select  TENTHELOAI, count(*) as dem, ROUND(count(*)/@tong,2) as tyle
	from sach a join CT_PHIEUMUON b  on a.MASACH = b.MASACH join phieumuon c on b.MAPHIEUMUON = c.MAPHIEUMUON join THELOAISACH d on a.MATHELOAISACH = d.MATHELOAISACH
	where C.NGAYMUON >= @DATEFROM AND C.NGAYMUON <= @DATETO
	group by TENTHELOAI 
END

EXEC REPORTBOOKUNRETURN @DATEFROM = '1/1/2020' , @DATETO = '5/6/2021'







