create database QuanLiThuVien
use QuanLiThuVien
set dateformat dmy

CREATE TABLE SACH
(
	MASACH CHAR(10) PRIMARY KEY,
	TENSACH NVARCHAR(30),
	TENTACGIA NVARCHAR(30),
	CALLNUMBER NVARCHAR(20),
	LOAISACH NVARCHAR(20),
	GIATRI MONEY,
	ISBN NVARCHAR(20),
	NHAXUATBAN NVARCHAR(20),
	HIENTRANG NVARCHAR(20) DEFAULT N'Chưa được mượn'
)
CREATE TABLE DOCGIA
(
	MADOCGIA CHAR(10) PRIMARY KEY,
	HOTEN NVARCHAR(100),
	DIACHI NVARCHAR(100),
	EMAIL NVARCHAR(100),
	CONGVIEC NVARCHAR(100),
	NGAYSINH DATE,
	GIOITINH NVARCHAR(10),
	SODIENTHOAI NVARCHAR(20),
	)
CREATE TABLE QUYDINH
(
	TIENPHATTRASACH MONEY,
	TUOIMAX INT,
	TUOIMIN INT,
	SONGAYDUOCMUON INT,
	SOSACHDUOCMUON INT,
	KCNAMXUATBAN INT,
	SACHTOIDADUOCMUON INT,
	SONGAYMUONTOIDA INT,
)
CREATE TABLE PHIEUMUON
(
	MAPM INT IDENTITY PRIMARY KEY,
	MADOCGIA CHAR(10),
	MANHANVIEN CHAR(10),
)
-----TẠO KHÓA NGOẠI CHO BẢNG PHIẾU MƯỢN
	ALTER TABLE PHIEUMUON
	ADD CONSTRAINT  FK_MADOCGIA  FOREIGN KEY (MADOCGIA)  REFERENCES DOCGIA (MADOCGIA)
	ALTER TABLE PHIEUMUON
	ADD CONSTRAINT  FK_MANHANVIEN  FOREIGN KEY (MANHANVIEN)  REFERENCES NHANVIEN (MANV)


CREATE TABLE CT_PHIEUMUON
(
	
	MAPM CHAR(10),
	MASACH CHAR(10),
	NGAYMUON DATE DEFAULT GETDATE(),
	NGAYTRA DATE,
	GHICHU NVARCHAR(100)
	constraint pk_CTPHIEUMUON primary key(MAPM,MASACH),
)
--CREATE TABLE PHIEUTRA
--(
--	MAPT CHAR(10) PRIMARY KEY,
--	MADOCGIA CHAR(10),
--	NGAYTRA DATETIME,
--	TIENPHATSACH MONEY,
--)
--CREATE TABLE CT_PHIEUTRA
--(
--	MAPT CHAR(10),
--	MASACH CHAR(10),
--	constraint pk_CTPHIEUTRA primary key(MAPT,MASACH),
--)

CREATE TABLE NHANVIEN
(
	MANV CHAR(10) PRIMARY KEY,
	TENNV NVARCHAR(20),
	NGAYSINH DATE,
	EMAIL NVARCHAR(30),
	GIOITINH NVARCHAR(10),
	SODT NVARCHAR(20),
	TAIKHOAN NVARCHAR(20) NOT NULL DEFAULT  'ACCOUNT',
	MATKHAU NVARCHAR(20) NOT NULL DEFAULT '123' ,
	TYPE INT NOT NULL DEFAULT 0 -- 1 là thủ thư , 0 là nhân viên
)


CREATE TABLE PHIEUTHANHTOAN
(
	MAPHIEUTHANHTOAN CHAR(10) PRIMARY KEY,
	MADOCGIA CHAR(10),
	MANGUOILAP CHAR(10),
	SOTIENTHANHTOAN MONEY,
	NGAYLAPTHANHTOAN DATETIME,
)
CREATE TABLE PHIEUYEUCAU
(
	MAPHIEUYEUCAU CHAR(10) PRIMARY KEY,
	MADOCGIA CHAR(10),
	MANGUOILAP CHAR(10),
	CHITIETYEUCAU NVARCHAR(40),
	NGAYLAPPHIEUYEUCAU DATETIME,
)
CREATE TABLE PHIEUBIENBANSUCO
(
	MASUCO CHAR(10) PRIMARY KEY,
	MADOCGIA CHAR(10),
	MASACH CHAR(10),
	NGAYLAPBIENBAN DATETIME,
	CHITIETSUCO NVARCHAR(30),
	SOTIENBOITHUONG MONEY,
)



INSERT INTO SACH(	MASACH ,	TENSACH ,	TENTACGIA ,	CALLNUMBER,	LOAISACH,	GIATRI,	ISBN ,	NHAXUATBAN  )
VALUES ('MS001', N'Mắt biếc', N'Nguyễn Nhật Ánh', 'Deway', N'Truyện' ,93000, 'HCM', N'NXB Kim Đồng')
INSERT INTO SACH(	MASACH ,	TENSACH ,	TENTACGIA ,	CALLNUMBER,	LOAISACH,	GIATRI,	ISBN ,	NHAXUATBAN  )
VALUES ('MS002', N'Cho tôi xin một vé đi tuổi thơ', N'Nguyễn Nhật Ánh', 'Deway',N'Truyện', 98000, 'HCM', N'NXB Kim Đồng')
INSERT INTO SACH(	MASACH ,	TENSACH ,	TENTACGIA ,	CALLNUMBER,	LOAISACH,	GIATRI,	ISBN ,	NHAXUATBAN  )
VALUES ('MS003', N'Tối là bêto', N'Nguyễn Nhật Ánh', 'Deway',N'Truyện', 60000, 'HCM', N'NXB Kim Đồng')
INSERT INTO SACH(	MASACH ,	TENSACH ,	TENTACGIA ,	CALLNUMBER,	LOAISACH,	GIATRI,	ISBN ,	NHAXUATBAN  )
VALUES ('MS004', N'Cô gái đến từ hôm qua', N'Nguyễn Nhật Ánh', 'Deway', N'Truyện', 78000, 'HCM', N'NXB Kim Đồng')
INSERT INTO SACH(	MASACH ,	TENSACH ,	TENTACGIA ,	CALLNUMBER,	LOAISACH,	GIATRI,	ISBN ,	NHAXUATBAN  )
VALUES ('MS005', N'Trại Hoa vàng', N'Nguyễn Nhật Ánh', 'Deway', N'Truyện', 88000, 'HCM', N'NXB Kim Đồng')
INSERT INTO SACH(	MASACH ,	TENSACH ,	TENTACGIA ,	CALLNUMBER,	LOAISACH,	GIATRI,	ISBN ,	NHAXUATBAN  )
VALUES ('MS006', N'Toán lớp 2', N'Nguyễn Xuân', 'Deway', N'SGK', 25000, 'HCM', N'NXB Giáo dục VN')
INSERT INTO SACH(	MASACH ,	TENSACH ,	TENTACGIA ,	CALLNUMBER,	LOAISACH,	GIATRI,	ISBN ,	NHAXUATBAN  )
VALUES ('MS007', N'Văn lớp 2', N'Lê An', 'Deway', N'SGK', 30000, 'HCM', N'NXB Giáo dục VN')
INSERT INTO SACH(	MASACH ,	TENSACH ,	TENTACGIA ,	CALLNUMBER,	LOAISACH,	GIATRI,	ISBN ,	NHAXUATBAN )
VALUES ('MS008', N'Báo hoa học trò', N'Lê An', 'Deway', N'Tạp chí', 5000, 'HCM', N'NXB Khoa Học Trẻ')


INSERT INTO DOCGIA ( MADOCGIA ,	 HOTEN ,	DIACHI ,	EMAIL,	CONGVIEC ,	NGAYSINH ,	GIOITINH ,	SODIENTHOAI)
VALUES ( 'DG001' , N'HOÀNG XUÂN VŨ', 'KTX KHU A', 'XUANVU001@GMAIL.COM', 'HỌC SINH', '26/01/2001', 'NAM', '0379678678')
INSERT INTO DOCGIA (MADOCGIA ,	HOTEN ,	DIACHI ,	EMAIL,	CONGVIEC ,	NGAYSINH ,	GIOITINH ,	SODIENTHOAI )
VALUES ('DG002', N'LÊ DƯƠNG KHÁNH VIỆT', 'KTX KHU B', 'KHANHVIET@GMAIL.COM', 'HỌC SINH', '28/01/2001', 'NAM', '0379678678')
INSERT INTO DOCGIA (MADOCGIA ,	HOTEN ,	DIACHI ,	EMAIL,	CONGVIEC ,	NGAYSINH ,	GIOITINH ,	SODIENTHOAI)
VALUES ('DG003', N'ĐỖ NGUYỄN HOÀNG HUY', 'KTX KHU B', 'HOANGHUY@GMAIL.COM', 'HỌC SINH', '23/01/2001', 'NAM', '0379678678')
INSERT INTO DOCGIA (MADOCGIA ,	HOTEN ,	DIACHI ,	EMAIL,	CONGVIEC ,	NGAYSINH ,	GIOITINH ,	SODIENTHOAI)
VALUES ('DG004', N'LÊ VĂN NHÂN', 'KTX KHU A', 'LEVANNHAN@GMAIL.COM', 'HỌC SINH', '26/05/2001', 'NAM', '0379678678')
INSERT INTO DOCGIA (MADOCGIA ,	HOTEN ,	DIACHI ,	EMAIL,	CONGVIEC ,	NGAYSINH ,	GIOITINH ,	SODIENTHOAI )
VALUES ('DG005', N'LÊ THỊ XUÂN AN', 'KTX KHU A', 'XUANAN@GMAIL.COM', 'HỌC SINH', '03/07/2001', N'NU', '0379678678')




INSERT INTO NHANVIEN(	MANV ,	TENNV ,	NGAYSINH ,	EMAIL,	GIOITINH ,	SODT ,	TAIKHOAN , TYPE )
VALUES ('NV001', N'LÊ VĂN A', '20/01/2001', 'LEVANA20/01/2001', 'NAM', '0479708321', 'A1' , 1)
INSERT INTO NHANVIEN(	MANV ,	TENNV ,	NGAYSINH ,	EMAIL,	GIOITINH ,	SODT ,	TAIKHOAN, TYPE)
VALUES ('NV002', N'LÊ VĂN B', '20/01/2001', 'LEVANA20/01/2001', 'NU', '0479708321', 'A2' ,0)



-- PROC login
CREATE PROC USP_LOGIN
@TAIKHOAN NVARCHAR(100),@MATKHAU NVARCHAR(100)
AS
BEGIN
	SELECT * 
	FROM NHANVIEN
	WHERE TAIKHOAN = @TAIKHOAN AND MATKHAU = @MATKHAU
END

EXEC USP_LOGIN @TAIKHOAN = 'ACCOUNTNV001', @MATKHAU = '123'

-- PROC ĐỔI MẬT KHẨU
CREATE PROC USP_CHANGEPASSWORD
@TAIKHOAN NVARCHAR(100), @MATKHAUMOI NVARCHAR(100)
AS
BEGIN
	UPDATE NHANVIEN
	SET MATKHAU = @MATKHAUMOI
	WHERE TAIKHOAN =@TAIKHOAN
END

-- PROC bỏ dấu chuỗi
CREATE FUNCTION [dbo].[GetUnsignString](@strInput NVARCHAR(4000)) 
RETURNS NVARCHAR(4000)
AS
BEGIN     
    IF @strInput IS NULL RETURN @strInput
    IF @strInput = '' RETURN @strInput
    DECLARE @RT NVARCHAR(4000)
    DECLARE @SIGN_CHARS NCHAR(136)
    DECLARE @UNSIGN_CHARS NCHAR (136)

    SET @SIGN_CHARS       = N'ăâđêôơưàảãạáằẳẵặắầẩẫậấèẻẽẹéềểễệếìỉĩịíòỏõọóồổỗộốờởỡợớùủũụúừửữựứỳỷỹỵýĂÂĐÊÔƠƯÀẢÃẠÁẰẲẴẶẮẦẨẪẬẤÈẺẼẸÉỀỂỄỆẾÌỈĨỊÍÒỎÕỌÓỒỔỖỘỐỜỞỠỢỚÙỦŨỤÚỪỬỮỰỨỲỶỸỴÝ'+NCHAR(272)+ NCHAR(208)
    SET @UNSIGN_CHARS = N'aadeoouaaaaaaaaaaaaaaaeeeeeeeeeeiiiiiooooooooooooooouuuuuuuuuuyyyyyAADEOOUAAAAAAAAAAAAAAAEEEEEEEEEEIIIIIOOOOOOOOOOOOOOOUUUUUUUUUUYYYYYDD'

    DECLARE @COUNTER int
    DECLARE @COUNTER1 int
    SET @COUNTER = 1
 
    WHILE (@COUNTER <=LEN(@strInput))
    BEGIN   
      SET @COUNTER1 = 1
      --Tim trong chuoi mau
       WHILE (@COUNTER1 <=LEN(@SIGN_CHARS)+1)
       BEGIN
     IF UNICODE(SUBSTRING(@SIGN_CHARS, @COUNTER1,1)) = UNICODE(SUBSTRING(@strInput,@COUNTER ,1) )
     BEGIN           
          IF @COUNTER=1
              SET @strInput = SUBSTRING(@UNSIGN_CHARS, @COUNTER1,1) + SUBSTRING(@strInput, @COUNTER+1,LEN(@strInput)-1)                   
          ELSE
              SET @strInput = SUBSTRING(@strInput, 1, @COUNTER-1) +SUBSTRING(@UNSIGN_CHARS, @COUNTER1,1) + SUBSTRING(@strInput, @COUNTER+1,LEN(@strInput)- @COUNTER)    
              BREAK         
               END
             SET @COUNTER1 = @COUNTER1 +1
       END
      --Tim tiep
       SET @COUNTER = @COUNTER +1
    END
    RETURN @strInput
END


